version: 2.1
orbs:
  win: circleci/windows@2.4.0
jobs:

  lint-unit-39: &lint-unit
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade Flask
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            uname -m
            python --version
            pip --version
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            black --check setup.py flask_appbuilder
            flake8 flask_appbuilder
            mypy flask_appbuilder
            
            
            
workflows:
 version: 2
 python3.9:
   jobs:
     - lint-unit-39
