version: 2.1
orbs:
  win: circleci/windows@2.4.0
jobs:

  lint-unit-39: &lint-unit
    docker:
      - image: circleci/python:3.6.1

    
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            sudo apt-get update
            sudo apt-get install -y python-dev libldap2-dev libsasl2-dev libssl-dev
            python --version
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            uname -m
            pip --version
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            black --check setup.py flask_appbuilder 
            
  test-postgres: 
    machine:
      image: ubuntu-2004:202101-01
    
    working_directory: ~/python-lz4
    steps:      
      - checkout
      - run:
          name: ️️requirements
          command: |
             uname -m 
             sudo apt-get update && sudo apt-get -y install python3 python3-pip 
             sudo apt-get install -y build-essential python3-dev libldap2-dev libsasl2-dev libssl-dev libmysqlclient-dev libpq-dev freetds-bin unixodbc-dev tdsodbc --yes
             python3 -m pip install -U pip 
             python3 setup.py install 
             pip3 install -r requirements.txt
             pip3 install -r requirements-dev.txt
             pip3 install -r requirements-extra.txt
      - run:
          name: ️️test
          command: |
             tox -e py38  
             
  build-medium-amd64:
    machine:
      image: ubuntu-2004:202101-01
   
    working_directory: ~/python-lz4
    steps:      
      - checkout
      - run:
          name: ️️requirements
          command: |
             uname -m 
             sudo apt-get update && sudo apt-get -y install python3 python3-pip 
             sudo apt-get install -y build-essential python3-dev libldap2-dev libsasl2-dev libssl-dev libmysqlclient-dev libpq-dev freetds-bin unixodbc-dev tdsodbc --yes
             python3 -m pip install -U pip 
             python3 setup.py install 
             pip3 install -r requirements.txt
             pip3 install -r requirements-dev.txt
             pip3 install -r requirements-extra.txt
      - run:
          name: ️️test
          command: |
             tox -e py38    
  
  build-medium-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/python-lz4
    steps:
      
      - checkout
      - run:
          name: ️️requirements
          command: |
             uname -m 
             sudo apt-get update && sudo apt-get -y install python3 python3-pip 
             sudo apt-get install -y build-essential python3-dev libldap2-dev libsasl2-dev libssl-dev libmysqlclient-dev libpq-dev unixodbc-dev freetds-bin unixodbc-dev tdsodbc --yes
             python3 -m pip install -U pip 
             python3 setup.py install 
             pip3 install -r requirements.txt
             pip3 install -r requirements-dev.txt
             pip3 install -r requirements-extra.txt
      - run:
          name: ️️test
          command: |
             tox -e py38           
workflows:
 version: 2
 python3.9:
   jobs:
     - lint-unit-39
     - test-postgres
     - build-medium-amd64
     - build-medium-arm64
